### ISSUE TITLE
"Question not Found" - show the question.

### ISSUE THREAD

**Issue by everton-amorim** [suiteplus/ns-export#6]
"Question not Found" - show the question.

**Comment by danieljoppi** [comment]
Its not a bug ... you can see the question in `.ns-exports/ss/question.jpg`.

But I added more information about that, like this:

``` bash
############################################
========>>> ns-export starting <<<==========
--------------------------------------------
account: #####
user: daniel.joppi@suiteplus.etc.br
hostname: https://system.na1.netsuite.com
############################################
[error] [phantom] Question not found
[error] [phantom] See the question in: .ns-exports/ss/question.jpg
```

**Comment by heathf** [comment]
I know this is closed, but I didn't want to open a new one since you specifically said it's not a bug, so I figured I'd just drop a comment here.  

I'm actually getting the same message, and I have triple checked the quiz section in my nsconfig.json file.  The question definitely matches my NetSuite security questions, word for word as well as from a case perspective.   

The question in the question.jpg is 'What street did you live on when you were 10 years old?'.   Here is my nsconfig.json contents, and it resides in my ~/.ns directory.  

```
{
    "account": 12345, 
    "realm": "sandbox.netsuite.com", 
    "script": 198, 
    "quiz": [
        {
            "question": "What street did you live on when you were 10 years old?",
            "answer": "MyAnswer" 
        }, 
        {
            "question": "What is your oldest sibling's middle name?",
            "answer": "MyAnswer"
        }, 
        {
            "question": "In what city or town was your first job?",
            "answer": "MyAnswer"
        }
    ], 
    "deployment": 1, 
    "password": "######", 
    "email": "#######"
}  
```

The output I'm getting is 

[error] [phantom] Question not found
[error] [phantom] See the question in: .ns-exports/ss/question.jpg

I'm not sure what else to check.  I know the answers I'm providing in nsconfig.json are also correct, because I went through the process of changing my password in our Sandbox instance, just to verify the security answers were what I expect them to be.   Also, I noticed the 'security questions must be lowercased' comment on the GitHub page, and I tried that as well.  I also tried lowercasing my answers, but I get the same message either way.

It looks like a great utility, so I'd love to get it working, if you can see anything obvious I'm doing wrong. 

Thanks

**Comment by heathf** [comment]
Never mind.  I actually got it working.  I had to put the nsconfig in my current directory.  It wouldn't work using nsconfig in my ~/.ns folder.  I'm not sure if that's a bug or not, but this works fine for me.  

Thanks
