### ISSUE TITLE
Wrong sysURL

### ISSUE THREAD

**Issue by ghost** [suiteplus/ns-export#7]
The export tool should not build an url with a fixed subdomain part. If i want to use the sandbox the url is: _system.sandbox.netsuite.com_ and not _system2.sandbox.netsuite.com_

```
var base = config.realm ? 'system2.' + config.realm : 'system.2netsuite.com',
```

Perhaps it would be better if we can define the whole url in nsconfig.json

```
var base = config.realm ? config.realm : 'system.netsuite.com', 
```

**Comment by danieljoppi** [comment]
You can not change it because it will create a conflict with [nscabinet](https://github.com/suiteplus/nscabinet). Both use [nsconfig](https://github.com/suiteplus/nsconfig) to get this configuration.
We can do ... is create a new config to set others `subRealm` ... by default is `system2`.

`config.realm` can be:
- `netsuite.com`
- `na1.netsuite.com`
- `na2.netsuite.com`
- _others_ ...

and `config.subRealm` can be:
- `system`
- `system2`
- `system.sandbox`
- _others_ ...

##### like that ...

``` javascript
var sub = config.subRealm || 'system2',
    realm = config.realm || 'netsuite.com',
    base = sub + '.' + realm,
// ...
```

what you think? ... submit your pull request :smiley:

**Comment by timaschew** [comment]
I have some questions:
Where is this doocumented that there are
- na1.netsuite.com
- na2.netsuite.com
- system2

Using a `subRealm` seems too complicated too me
Why not just let the user pass the whole hostname, this makes everything much simpler.

> You can not change it because it will create a conflict with nscabinet. Both use nsconfig to get this configuration.

Sometimes it's time for a breaking change ;)

**Comment by danieljoppi** [comment]
like that?

``` javascript
var realm = config.realm || 'netsuite.com',
    base = config.hostname || 'system2.' + realm,
// ...
```

**Comment by timaschew** [comment]
Okay sounds good. But is `system2` the default, if yes why?

**Comment by danieljoppi** [comment]
whatever ... ehehehhehe

**Comment by timaschew** [comment]
system2 won't work for the sandbox :P
